EVALUATE
VAR _Hoy = TODAY ()

VAR _BasePendientes =
    FILTER (
        'CIAMDA VistaMAIMantenimiento',
        NOT CONTAINSSTRING (
            UPPER ( COALESCE ( 'CIAMDA VistaMAIMantenimiento'[ESTATUS], "" ) ),
            "CERRADO"
        )
            && NOT CONTAINSSTRING (
                UPPER ( COALESCE ( 'CIAMDA VistaMAIMantenimiento'[ESTATUS_MAI], "" ) ),
                "CERRADA"
            )
    )

VAR _ConDias =
    ADDCOLUMNS (
        _BasePendientes,

        "DIAS_ABIERTO",
            DATEDIFF (
                'CIAMDA VistaMAIMantenimiento'[FECHA SOLICITUD],
                _Hoy,
                DAY
            ),

        "DIAS_PROVEEDOR",
            IF (
                NOT ISBLANK ( 'CIAMDA VistaMAIMantenimiento'[FECHA REPORTE AL PROVEEDOR] ),
                DATEDIFF (
                    'CIAMDA VistaMAIMantenimiento'[FECHA REPORTE AL PROVEEDOR],
                    _Hoy,
                    DAY
                ),
                BLANK ()
            )
    )

VAR _ConPrioridad =
    ADDCOLUMNS (
        _ConDias,

        "PRIORIDAD_NUM",
            SWITCH (
                TRUE (),

                NOT ISBLANK ( 'CIAMDA VistaMAIMantenimiento'[FECHA REPORTE AL PROVEEDOR] )
                    && ISBLANK ( 'CIAMDA VistaMAIMantenimiento'[FECHA ENTREGA] )
                    && [DIAS_PROVEEDOR] > 30,
                    1,

                NOT ISBLANK ( 'CIAMDA VistaMAIMantenimiento'[FECHA REPORTE AL PROVEEDOR] )
                    && ISBLANK ( 'CIAMDA VistaMAIMantenimiento'[FECHA ENTREGA] )
                    && [DIAS_PROVEEDOR] > 1,
                    2,

                ISBLANK ( 'CIAMDA VistaMAIMantenimiento'[FECHA DIAGNOSTICO] )
                    && [DIAS_ABIERTO] > 5,
                    3,

                [DIAS_ABIERTO] > 30,
                    4,

                5
            )
    )

VAR _Salida =
    ADDCOLUMNS (
        _ConPrioridad,

        "PRIORIDAD_TXT",
            SWITCH (
                TRUE (),
                [PRIORIDAD_NUM] = 1, "CRITICA",
                [PRIORIDAD_NUM] = 2, "ALTA",
                [PRIORIDAD_NUM] = 3, "ALTA INTERNA",
                [PRIORIDAD_NUM] = 4, "DEPURAR",
                "NORMAL"
            ),

        "BLOQUE_OPERATIVO",
            SWITCH (
                TRUE (),

                [PRIORIDAD_NUM] = 1,
                    "CRITICO 30D / GARANTIA VENCIDA",

                [PRIORIDAD_NUM] = 2,
                    "CRITICO 24H / PROVEEDOR SIN CIERRE",

                CONTAINSSTRING (
                    UPPER ( COALESCE ( 'CIAMDA VistaMAIMantenimiento'[SEGUIMIENTO], "" ) ),
                    "NO FACILITO"
                )
                    || CONTAINSSTRING (
                        UPPER ( COALESCE ( 'CIAMDA VistaMAIMantenimiento'[SEGUIMIENTO], "" ) ),
                        "NO SE HA RECIBIDO RESPUESTA"
                    )
                    || CONTAINSSTRING (
                        UPPER ( COALESCE ( 'CIAMDA VistaMAIMantenimiento'[SEGUIMIENTO], "" ) ),
                        "A PRUEBA"
                    ),
                    "PENDIENTE USUARIO / VALIDAR CIERRE",

                [PRIORIDAD_NUM] = 3,
                    "INTERNO VENCIDO / SIN DIAGNOSTICO",

                [PRIORIDAD_NUM] = 4,
                    "DEPURACION HISTORICA",

                NOT ISBLANK ( 'CIAMDA VistaMAIMantenimiento'[FECHA REPORTE AL PROVEEDOR] ),
                    "GARANTIA EN CURSO",

                "SEGUIMIENTO ORDINARIO"
            ),

        "ACCION_RECOMENDADA",
            SWITCH (
                TRUE (),

                [PRIORIDAD_NUM] = 1,
                    "Revisar contrato/SLA. Preparar escalamiento por vencimiento de 30 dias, sustitucion o penalizacion preliminar.",

                [PRIORIDAD_NUM] = 2,
                    "Escalar con proveedor. Solicitar respuesta formal, guia, reparacion, sustitucion o fecha compromiso.",

                CONTAINSSTRING (
                    UPPER ( COALESCE ( 'CIAMDA VistaMAIMantenimiento'[SEGUIMIENTO], "" ) ),
                    "A PRUEBA"
                ),
                    "Contactar usuario. Confirmar funcionamiento y cerrar si procede.",

                [PRIORIDAD_NUM] = 3,
                    "Solicitar diagnostico al tecnico asignado o depurar causa de falta de avance.",

                [PRIORIDAD_NUM] = 4,
                    "Validar si el caso debe cerrarse, corregirse o reclasificarse como historico.",

                "Continuar seguimiento ordinario."
            ),

        "RIESGO_DATO",
            SWITCH (
                TRUE (),

                CONTAINSSTRING (
                    UPPER ( COALESCE ( 'CIAMDA VistaMAIMantenimiento'[SEGUIMIENTO], "" ) ),
                    "TICKET: ;"
                )
                    || CONTAINSSTRING (
                        UPPER ( COALESCE ( 'CIAMDA VistaMAIMantenimiento'[SEGUIMIENTO], "" ) ),
                        "TICKET:"
                    )
                        && CONTAINSSTRING (
                            UPPER ( COALESCE ( 'CIAMDA VistaMAIMantenimiento'[SEGUIMIENTO], "" ) ),
                            "GENERANDO EL TICKET:"
                        )
                        && LEN (
                            TRIM (
                                SUBSTITUTE (
                                    UPPER ( COALESCE ( 'CIAMDA VistaMAIMantenimiento'[SEGUIMIENTO], "" ) ),
                                    "GENERANDO EL TICKET:",
                                    ""
                                )
                            )
                        ) = 0,
                    "VALIDAR NUMERO DE TICKET",

                "OK"
            )
    )

RETURN
SELECTCOLUMNS (
    _Salida,

    "ORDEN", [PRIORIDAD_NUM],
    "PRIORIDAD", [PRIORIDAD_TXT],
    "BLOQUE OPERATIVO", [BLOQUE_OPERATIVO],
    "ACCION RECOMENDADA", [ACCION_RECOMENDADA],
    "RIESGO DATO", [RIESGO_DATO],

    "CODIGO", 'CIAMDA VistaMAIMantenimiento'[CODIGO],
    "AÑO", 'CIAMDA VistaMAIMantenimiento'[AÑO],
    "URL REPORTE", 'CIAMDA VistaMAIMantenimiento'[Reporte impreso],

    "DIAS ABIERTO", [DIAS_ABIERTO],
    "DIAS PROVEEDOR", [DIAS_PROVEEDOR],

    "ESTATUS", 'CIAMDA VistaMAIMantenimiento'[ESTATUS],
    "ESTATUS_MAI", 'CIAMDA VistaMAIMantenimiento'[ESTATUS_MAI],
    "DESCRIP STATUS", 'CIAMDA VistaMAIMantenimiento'[descrip status],

    "FECHA SOLICITUD", 'CIAMDA VistaMAIMantenimiento'[FECHA SOLICITUD],
    "FECHA INICIO SERVICIO", 'CIAMDA VistaMAIMantenimiento'[FECHA INICIO SERVICIO],
    "FECHA RECEPCION EQUIPO", 'CIAMDA VistaMAIMantenimiento'[FECHA RECEPCION EQUIPO],
    "FECHA DIAGNOSTICO", 'CIAMDA VistaMAIMantenimiento'[FECHA DIAGNOSTICO],
    "FECHA REPORTE PROVEEDOR", 'CIAMDA VistaMAIMantenimiento'[FECHA REPORTE AL PROVEEDOR],
    "FECHA EQUIPO REPARADO O RESPALDO", 'CIAMDA VistaMAIMantenimiento'[FECHA EQUIPO REPARADO],
    "FECHA ENTREGA", 'CIAMDA VistaMAIMantenimiento'[FECHA ENTREGA],

    "PROVEEDOR", 'CIAMDA VistaMAIMantenimiento'[PROVEEDOR],
    "CONTRATO", 'CIAMDA VistaMAIMantenimiento'[CONTRATO],
    "CLIENTE", 'CIAMDA VistaMAIMantenimiento'[CLIENTE],
    "E-MAIL", 'CIAMDA VistaMAIMantenimiento'[E-MAIL],
    "EXTENSION", 'CIAMDA VistaMAIMantenimiento'[EXTENSION],
    "ENTIDAD", 'CIAMDA VistaMAIMantenimiento'[ENTIDAD],
    "AREA", 'CIAMDA VistaMAIMantenimiento'[AREA],
    "ADSCRIPCION", 'CIAMDA VistaMAIMantenimiento'[ADSCRIPCION],

    "TIPO SERVICIO", 'CIAMDA VistaMAIMantenimiento'[TIPO SERVICIO],
    "TIPO EQUIPO", 'CIAMDA VistaMAIMantenimiento'[TIPO EQUIPO],
    "MARCA", 'CIAMDA VistaMAIMantenimiento'[MARCA],
    "MODELO", 'CIAMDA VistaMAIMantenimiento'[MODELO],
    "SERIE", 'CIAMDA VistaMAIMantenimiento'[SERIE],
    "SERIE CPU PERIFERICO", 'CIAMDA VistaMAIMantenimiento'[SERIE CPU PERIFERICO],
    "INVENTARIO", 'CIAMDA VistaMAIMantenimiento'[INVENTARIO],
    "ESTADO FISICO", 'CIAMDA VistaMAIMantenimiento'[ESTADO FISICO],

    "FALLA REPORTADA", 'CIAMDA VistaMAIMantenimiento'[FALLA REPORTADA],
    "SOLUCION", 'CIAMDA VistaMAIMantenimiento'[SOLUCION],
    "OBSERVACIONES", 'CIAMDA VistaMAIMantenimiento'[OBSERVACIONES],
    "SEGUIMIENTO", 'CIAMDA VistaMAIMantenimiento'[SEGUIMIENTO],

    "ATENDIDO POR", 'CIAMDA VistaMAIMantenimiento'[ATENDIDO POR],
    "ASIGNADO A", 'CIAMDA VistaMAIMantenimiento'[ASIGNADO A]
)
ORDER BY
    [ORDEN] ASC,
    [DIAS PROVEEDOR] DESC,
    [DIAS ABIERTO] DESC,
    [FECHA SOLICITUD] ASC
