-- Garantías INEGI · Export operativo a Excel SharePoint
-- Sustituye NOMBRE_REAL_DE_TABLA y los nombres de columna entre corchetes por los nombres reales del modelo.
-- Regla: NO usa PRIORIDAD_NUM como columna física. La prioridad se calcula como columna virtual __ORDEN.

EVALUATE
VAR _Base =
    FILTER (
        'NOMBRE_REAL_DE_TABLA',
        NOT ISBLANK ( 'NOMBRE_REAL_DE_TABLA'[CODIGO] )
    )
VAR _Scored =
    ADDCOLUMNS (
        _Base,
        "__DIAS_PROVEEDOR_SAFE", COALESCE ( 'NOMBRE_REAL_DE_TABLA'[DIAS PROVEEDOR], 0 ),
        "__DIAS_ABIERTO_SAFE", COALESCE ( 'NOMBRE_REAL_DE_TABLA'[DIAS ABIERTO], 0 ),
        "__ORDEN",
            VAR _estatus = UPPER ( COALESCE ( 'NOMBRE_REAL_DE_TABLA'[ESTATUS], "" ) )
            VAR _tipoServicio = UPPER ( COALESCE ( 'NOMBRE_REAL_DE_TABLA'[TIPO SERVICIO], "" ) )
            VAR _riesgo = UPPER ( COALESCE ( 'NOMBRE_REAL_DE_TABLA'[RIESGO DATO], "" ) )
            VAR _diasProveedor = COALESCE ( 'NOMBRE_REAL_DE_TABLA'[DIAS PROVEEDOR], 0 )
            VAR _diasAbierto = COALESCE ( 'NOMBRE_REAL_DE_TABLA'[DIAS ABIERTO], 0 )
            RETURN
                SWITCH (
                    TRUE (),
                    _tipoServicio = "CON GARANTÍA" && _diasProveedor >= 30 && _estatus = "PENDIENTE", 1,
                    _tipoServicio = "CON GARANTÍA" && _diasProveedor >= 2 && _estatus = "PENDIENTE", 2,
                    _tipoServicio = "INTERNO" && _diasAbierto >= 7 && _estatus = "REVISION", 3,
                    _riesgo <> "" && _riesgo <> "OK", 4,
                    5
                ),
        "__PRIORIDAD",
            VAR _tipoServicio = UPPER ( COALESCE ( 'NOMBRE_REAL_DE_TABLA'[TIPO SERVICIO], "" ) )
            VAR _estatus = UPPER ( COALESCE ( 'NOMBRE_REAL_DE_TABLA'[ESTATUS], "" ) )
            VAR _diasProveedor = COALESCE ( 'NOMBRE_REAL_DE_TABLA'[DIAS PROVEEDOR], 0 )
            VAR _diasAbierto = COALESCE ( 'NOMBRE_REAL_DE_TABLA'[DIAS ABIERTO], 0 )
            RETURN
                SWITCH (
                    TRUE (),
                    _tipoServicio = "CON GARANTÍA" && _diasProveedor >= 30 && _estatus = "PENDIENTE", "CRITICA",
                    _tipoServicio = "CON GARANTÍA" && _diasProveedor >= 2 && _estatus = "PENDIENTE", "ALTA",
                    _tipoServicio = "INTERNO" && _diasAbierto >= 7 && _estatus = "REVISION", "ALTA INTERNA",
                    "NORMAL"
                ),
        "__BLOQUE_OPERATIVO",
            VAR _tipoServicio = UPPER ( COALESCE ( 'NOMBRE_REAL_DE_TABLA'[TIPO SERVICIO], "" ) )
            VAR _estatus = UPPER ( COALESCE ( 'NOMBRE_REAL_DE_TABLA'[ESTATUS], "" ) )
            VAR _diasProveedor = COALESCE ( 'NOMBRE_REAL_DE_TABLA'[DIAS PROVEEDOR], 0 )
            VAR _diasAbierto = COALESCE ( 'NOMBRE_REAL_DE_TABLA'[DIAS ABIERTO], 0 )
            RETURN
                SWITCH (
                    TRUE (),
                    _tipoServicio = "CON GARANTÍA" && _diasProveedor >= 30 && _estatus = "PENDIENTE", "CRITICO 30D / GARANTIA VENCIDA",
                    _tipoServicio = "CON GARANTÍA" && _diasProveedor >= 2 && _estatus = "PENDIENTE", "CRITICO 24H / PROVEEDOR SIN CIERRE",
                    _tipoServicio = "INTERNO" && _diasAbierto >= 7 && _estatus = "REVISION", "INTERNO VENCIDO / SIN DIAGNOSTICO",
                    "SEGUIMIENTO ORDINARIO"
                ),
        "__ACCION_RECOMENDADA",
            VAR _tipoServicio = UPPER ( COALESCE ( 'NOMBRE_REAL_DE_TABLA'[TIPO SERVICIO], "" ) )
            VAR _estatus = UPPER ( COALESCE ( 'NOMBRE_REAL_DE_TABLA'[ESTATUS], "" ) )
            VAR _diasProveedor = COALESCE ( 'NOMBRE_REAL_DE_TABLA'[DIAS PROVEEDOR], 0 )
            VAR _diasAbierto = COALESCE ( 'NOMBRE_REAL_DE_TABLA'[DIAS ABIERTO], 0 )
            RETURN
                SWITCH (
                    TRUE (),
                    _tipoServicio = "CON GARANTÍA" && _diasProveedor >= 30 && _estatus = "PENDIENTE", "Revisar contrato/SLA. Preparar escalamiento por vencimiento de 30 dias, sustitucion o penalizacion preliminar.",
                    _tipoServicio = "CON GARANTÍA" && _diasProveedor >= 2 && _estatus = "PENDIENTE", "Escalar con proveedor. Solicitar respuesta formal, guia, reparacion, sustitucion o fecha compromiso.",
                    _tipoServicio = "INTERNO" && _diasAbierto >= 7 && _estatus = "REVISION", "Solicitar diagnostico al tecnico asignado o depurar causa de falta de avance.",
                    "Continuar seguimiento ordinario."
                ),
        "__RIESGO_DATO",
            VAR _seguimiento = UPPER ( COALESCE ( 'NOMBRE_REAL_DE_TABLA'[SEGUIMIENTO], "" ) )
            VAR _serie = UPPER ( COALESCE ( 'NOMBRE_REAL_DE_TABLA'[SERIE], "" ) )
            VAR _ticketVacio = CONTAINSSTRING ( _seguimiento, "TICKET:" ) && NOT CONTAINSSTRING ( _seguimiento, "TICKET: 0" ) && RIGHT ( TRIM ( _seguimiento ), 7 ) = "TICKET:"
            RETURN
                SWITCH (
                    TRUE (),
                    ISBLANK ( 'NOMBRE_REAL_DE_TABLA'[CODIGO] ), "VALIDAR CODIGO",
                    ISBLANK ( 'NOMBRE_REAL_DE_TABLA'[AÑO] ), "VALIDAR AÑO",
                    _serie = "" || _serie = "INDICAR SERIE", "VALIDAR SERIE",
                    _ticketVacio, "VALIDAR NUMERO DE TICKET",
                    "OK"
                )
    )
RETURN
SELECTCOLUMNS (
    _Scored,
    "ORDEN", [__ORDEN],
    "PRIORIDAD", [__PRIORIDAD],
    "BLOQUE OPERATIVO", [__BLOQUE_OPERATIVO],
    "ACCION RECOMENDADA", [__ACCION_RECOMENDADA],
    "RIESGO DATO", [__RIESGO_DATO],
    "CODIGO", 'NOMBRE_REAL_DE_TABLA'[CODIGO],
    "AÑO", 'NOMBRE_REAL_DE_TABLA'[AÑO],
    "URL REPORTE", 'NOMBRE_REAL_DE_TABLA'[URL REPORTE],
    "DIAS ABIERTO", 'NOMBRE_REAL_DE_TABLA'[DIAS ABIERTO],
    "DIAS PROVEEDOR", 'NOMBRE_REAL_DE_TABLA'[DIAS PROVEEDOR],
    "ESTATUS", 'NOMBRE_REAL_DE_TABLA'[ESTATUS],
    "ESTATUS_MAI", 'NOMBRE_REAL_DE_TABLA'[ESTATUS_MAI],
    "DESCRIP STATUS", 'NOMBRE_REAL_DE_TABLA'[DESCRIP STATUS],
    "FECHA SOLICITUD", 'NOMBRE_REAL_DE_TABLA'[FECHA SOLICITUD],
    "FECHA INICIO SERVICIO", 'NOMBRE_REAL_DE_TABLA'[FECHA INICIO SERVICIO],
    "FECHA RECEPCION EQUIPO", 'NOMBRE_REAL_DE_TABLA'[FECHA RECEPCION EQUIPO],
    "FECHA DIAGNOSTICO", 'NOMBRE_REAL_DE_TABLA'[FECHA DIAGNOSTICO],
    "FECHA REPORTE PROVEEDOR", 'NOMBRE_REAL_DE_TABLA'[FECHA REPORTE PROVEEDOR],
    "FECHA EQUIPO REPARADO O RESPALDO", 'NOMBRE_REAL_DE_TABLA'[FECHA EQUIPO REPARADO O RESPALDO],
    "FECHA ENTREGA", 'NOMBRE_REAL_DE_TABLA'[FECHA ENTREGA],
    "PROVEEDOR", 'NOMBRE_REAL_DE_TABLA'[PROVEEDOR],
    "CONTRATO", 'NOMBRE_REAL_DE_TABLA'[CONTRATO],
    "CLIENTE", 'NOMBRE_REAL_DE_TABLA'[CLIENTE],
    "E-MAIL", 'NOMBRE_REAL_DE_TABLA'[E-MAIL],
    "EXTENSION", 'NOMBRE_REAL_DE_TABLA'[EXTENSION],
    "ENTIDAD", 'NOMBRE_REAL_DE_TABLA'[ENTIDAD],
    "AREA", 'NOMBRE_REAL_DE_TABLA'[AREA],
    "ADSCRIPCION", 'NOMBRE_REAL_DE_TABLA'[ADSCRIPCION],
    "TIPO SERVICIO", 'NOMBRE_REAL_DE_TABLA'[TIPO SERVICIO],
    "TIPO EQUIPO", 'NOMBRE_REAL_DE_TABLA'[TIPO EQUIPO],
    "MARCA", 'NOMBRE_REAL_DE_TABLA'[MARCA],
    "MODELO", 'NOMBRE_REAL_DE_TABLA'[MODELO],
    "SERIE", 'NOMBRE_REAL_DE_TABLA'[SERIE],
    "SERIE CPU PERIFERICO", 'NOMBRE_REAL_DE_TABLA'[SERIE CPU PERIFERICO],
    "INVENTARIO", 'NOMBRE_REAL_DE_TABLA'[INVENTARIO],
    "ESTADO FISICO", 'NOMBRE_REAL_DE_TABLA'[ESTADO FISICO],
    "FALLA REPORTADA", 'NOMBRE_REAL_DE_TABLA'[FALLA REPORTADA],
    "SOLUCION", 'NOMBRE_REAL_DE_TABLA'[SOLUCION],
    "OBSERVACIONES", 'NOMBRE_REAL_DE_TABLA'[OBSERVACIONES],
    "SEGUIMIENTO", 'NOMBRE_REAL_DE_TABLA'[SEGUIMIENTO],
    "ATENDIDO POR", 'NOMBRE_REAL_DE_TABLA'[ATENDIDO POR],
    "ASIGNADO A", 'NOMBRE_REAL_DE_TABLA'[ASIGNADO A]
)
ORDER BY
    [ORDEN] ASC,
    [DIAS PROVEEDOR] DESC,
    [DIAS ABIERTO] DESC,
    [CODIGO] ASC
